WebApplication1/Models/ErrorViewModel.cs
namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/ConvertidorController.cs
using Application.Service;
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ConvertidorController : Controller
    {
        public ConvertidorService ConvertidorService;

        public ConvertidorController()
        {
            ConvertidorService = new();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ConvertidorViewModel cv)
        {
            ConvertidorService.Convert(cv);
            double valor = ConvertidorService.GetAll();
            ViewBag.Valor = Math.Round(valor, 2);
            return View();
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication1/Controllers/PrestamosController.cs
using Application.Service;
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class PrestamosController : Controller
    {
        public PrestamosService PrestamosService;

        public PrestamosController()
        {
            PrestamosService = new PrestamosService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(PrestamosViewModel pm)
        {
            PrestamosService.SetPrestamo(pm);
            double testing = PrestamosService.GetAll();
            ViewBag.testing = Math.Round(testing,2); 
            return View();
        }
    }
}

WebApplication1/Controllers/ZodiacoController.cs
using Application.Service;
using Application.ViewModel;
using Microsoft.AspNetCore.Mvc;

namespace WebApplication1.Controllers
{
    public class ZodiacoController : Controller
    {
        public ZodiacoService ZodiacService;

        public ZodiacoController()
        {
            ZodiacService = new ZodiacoService();
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Index(ZodiacoViewModel zm)
        {
            ZodiacService.SetZodiaco(zm);
            string ZodiacData = ZodiacService.GetAll();
            ViewBag.ZodiacData = ZodiacData;
            return View();
        }
    }
}

WebApplication1/Views/Convertidor/Index.cshtml
@model Application.ViewModel.ConvertidorViewModel
@{
    ViewData["Title"] = "Create";
}

<h3 class="text-center">Convertidor de moneda</h3>

<div class="col-md-6 offset-3 mt-3">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="~/css/Images/coins2.jpg" class="" style="width: 210px; height: 350px;">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <form method="post" asp-action="Index" asp-for="Convertidor">

                        <div class="col-md-8 offset-md-2">
                            <label>Moneda actual: </label>
                            <select class="form-select" asp-for="Tipo">
                                <option value="1">Peso dominicano</option>
                                <option value="2">Dolar estado unidense</option>
                                <option value="3">Euro</option>
                            </select>
                        </div>

                        <div class="col-md-8 offset-md-2">
                            <label>Convertir a: </label>
                            <select class="form-select" asp-for="Tipo_Convertir">
                                <option value="1">Peso dominicano</option>
                                <option value="2">Dolar estado unidense</option>
                                <option value="3">Euro</option>
                            </select>
                        </div>

                        <div class="col-md-8 offset-md-2">
                            <label>Cantidad: </label>
                            <input type="text" asp-for="Cantidad" />
                        </div>

                        <button class="btn btn-primary bt-3 mt-3 col-md-8 offset-md-2">Calcular</button>

                    </form>

                    <h5 class="col-md-8 offset-md-2 mt-3">Resultado: <strong class="text-primary">@ViewBag.Valor</strong></h5>
                </div>
            </div>
        </div>
    </div>
</div>

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Homework #1 - controladores y vistas</h1>
    <p>Navegar con las opciones en la parte supeiorr.</p>
</div>

WebApplication1/Views/Prestamos/Index.cshtml
@model Application.ViewModel.PrestamosViewModel
@{
    ViewData["Title"] = "Calculadora de prestamos";
}


<div class="col-md-6 offset-3 mt-3">
    <h2>Calculadora de prestamos a plazos</h2>

    <form method="post" asp-action="Index" asp-for="Prestamos">

        <div>
            <label asp-for="Monto">Monto: </label>
            <input type="text" asp-for="Monto" />
        </div>

        <div>
            <label asp-for="Tipo_Prestamo">Tipo de prestamo: </label>
            <select class="form-select" asp-for="Tipo_Prestamo">
                <option value="1">Personal</option>
                <option value="2">Automovil</option>
                <option value="3">Hipotecario</option>
            </select>
        </div>

        <div>
            <label asp-for="Meses">Plazo en meses: </label>
            <select class="form-select" asp-for="Meses">
                @for (int i = 12; i < 121; i = i + 6){
                    <option value="@i">@i Meses</option>
                }
            </select>
        </div>

        <button class="btn btn-primary">Calcular</button>
    </form>

    <h5>Total a pagar: <strong class="text-primary">$ @ViewBag.testing</strong> Mensuales</h5>
</div>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication1.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication1</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Zodiaco" asp-action="Index">Zodiaco</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Convertidor" asp-action="Index">Convertir de monedas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Prestamos" asp-action="Index">Prestamos</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WebApplication1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebApplication1/Views/Zodiaco/Index.cshtml
@model Application.ViewModel.ZodiacoViewModel
@{
    ViewData["Title"] = "Create";
}

<h3 class="text-center">Conoce tu signo del zodiaco</h3>

<div class="col-md-6 offset-3">
    <form method="post" asp-action="Index" asp-for="Zodiaco">

        <div>
            <label asp-for="Dia" class="form-label">Dia:</label>
            <select class="form-select" asp-for="Dia">
                @for(int i=0; i<32; i++){
                    <option value="@i">@i</option>
                }
            </select>
        </div>

        <div>
            <label asp-for="Mes" class="form-label">Mes:</label>
            <select class="form-select" asp-for="Mes">
                @for (int i = 0; i < 13; i++)
                {
                    <option value="@i">@i</option>
                }
            </select>
        </div>

        <button class="btn btn-primary mb-3 col-md-6 offset-3 mt-3" type="submit">Send</button>

    </form>

    <h4 class="text-primary text-center mt-3">@ViewBag.ZodiacData</h4>
</div>